# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SLOOPS
version:      0.01
version_from: lib/SLOOPS.pm
installdirs:  site
requires:
    Class::AutoAccess:             0.02
    DBI:                           1.4
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
